MainModel refactoring
AleksandrMaslov/RevitSpacesManager_CSharp-WPF pull request #6
Opened 2022-11-16 19:13 UTC by AleksandrMaslov

Переработан безличный класс MainModel (был разделен на два класса SpacesModel и RoomsModel, связанные интерфейсом IModel). Второй необязательный toggle switch был удален, выбор объекта действия стал осуществляться единым переключателем. Изменение положения переключателя стало переводить в "активное" состояние одну из моделей, внутри которой уже будет реализовываться бизнес-логика работы с Rooms или Spaces. Из VM ушли лишние методы и свойства, котрые были связаны с ранее размещенными двумя перключателями.

В интерфейсе добавлено выделение цветом выбранного объекта действия, текстовый комментарий по выбору фазы вида и вынесено значение свойства, хранящее имя фазы текущего вида.

2022-11-17 08:01 UTC, PavelAltynnikov reviewed
При том что MainModel больше нет, IModel по сути это тоже самое)
И название такое же непонятное и вмещает в себе и бизнеслогику и VM части.

В классах бизнеслогики до сих пор нет реализации) Я думаю она частично изменит эти классы, но она не должна изменить интерфейсы, как у тебя это произошло в третьем коммите, когда в IModel добавилось куча всего, чего имхо там не должно быть. Опять же, наверное это добавилось потому, что нет понимания границ данного интерфейса.

Тумблер со спейсами и румами ну оч понтово выглядит!)

2022-11-18 13:59 UTC, AleksandrMaslov commented on RevitSpacesManager/ViewModels/MainWindowViewModel.cs
> +            // на view выделять цветом Space Room
ага, место неудачно выбрал, идею уяснил) удалил

2022-11-18 14:00 UTC, AleksandrMaslov commented on RevitSpacesManager/ViewModels/MainWindowViewModel.cs
> +        public bool AreSpacesChecked
Checked - от того что toggle switch сделан из checkbox'а, по сути галочка, пусть будет

2022-11-20 10:43 UTC, AleksandrMaslov commented on RevitSpacesManager/Models/IModel.cs
> +    internal interface IModel
> При том что MainModel больше нет, IModel по сути это тоже самое) И название такое же непонятное и вмещает в себе и бизнеслогику и VM части.
> В классах бизнеслогики до сих пор нет реализации) Я думаю она частично изменит эти классы, но она не должна изменить интерфейсы, как у тебя это произошло в третьем коммите, когда в IModel добавилось куча всего, чего имхо там не должно быть. Опять же, наверное это добавилось потому, что нет понимания границ данного интерфейса.

Да, было определенной непонимание границ интерефейса.  Свойства относящиеся к VM вернул в VM обратно, увлекса упрощением класса) Переработал интерефейс IModel в два отдельных интерфейса в соответствии с функциями и добавился абстрактный класс AreaModel. Благодарю за обсуждения!

> Тумблер со спейсами и румами ну оч понтово выглядит!)

Тумблер - главный мотиватор разработки приложения)))

2022-11-20 10:45 UTC, AleksandrMaslov commented
> При том что MainModel больше нет, IModel по сути это тоже самое) И название такое же непонятное и вмещает в себе и бизнеслогику и VM части.
> В классах бизнеслогики до сих пор нет реализации) Я думаю она частично изменит эти классы, но она не должна изменить интерфейсы, как у тебя это произошло в третьем коммите, когда в IModel добавилось куча всего, чего имхо там не должно быть. Опять же, наверное это добавилось потому, что нет понимания границ данного интерфейса.

Да, было определенной непонимание границ интерефейса.  Свойства относящиеся к VM вернул в VM обратно, увлекса упрощением класса) Переработал интерефейс IModel в два отдельных интерфейса в соответствии с функциями и добавился абстрактный класс AreaModel. Благодарю за обсуждения!

> Тумблер со спейсами и румами ну оч понтово выглядит!)

Тумблер - главный мотиватор разработки приложения)))

2022-11-20 19:45 UTC, PavelAltynnikov requested changes

2022-11-20 19:45 UTC, PavelAltynnikov commented on RevitSpacesManager/ViewModels/Commands/CreateAllCommand.cs
> +        public AreaModel Model { get; set; }
Зачем этой команде какая-та непонятная модель? Ей интерфейс нужен.
С остальными командами тоже самое.

2022-11-20 19:45 UTC, PavelAltynnikov commented on RevitSpacesManager/ViewModels/Commands/CreateAllCommand.cs
> +        public CreateAllCommand(MainWindowViewModel mainWindowViewModel, AreaModel model)
Тут тоже самое. Команда ничего не знает про модель, она хочет себе конкретный интерфейс, а кто его реализует, ей не важно.

2022-11-20 19:45 UTC, PavelAltynnikov commented on RevitSpacesManager/Models/RoomsModel.cs
> +            throw new NotImplementedException();
Ну раз уж нет реализации, то хотя бы экзепшены убери, а то даже в кнопки не сможешь потыкать в "тесте".

2022-11-20 19:45 UTC, PavelAltynnikov commented on RevitSpacesManager/ViewModels/MainWindowViewModel.cs
> +            DeleteAllCommand.Model = _activeModel;
Ты собираешь проект и проверяешь его работу в Revit? А то я запустил, а в этой строке NullReferenceException.

2022-11-21 06:22 UTC, AleksandrMaslov commented on RevitSpacesManager/ViewModels/MainWindowViewModel.cs
> +            DeleteAllCommand.Model = _activeModel;
Не запушил последний коммит вчера, там было исправлено

2022-11-21 06:25 UTC, AleksandrMaslov commented on RevitSpacesManager/Models/RoomsModel.cs
> +            throw new NotImplementedException();
Давай добавим раз хочется потыкать)

2022-11-21 06:29 UTC, AleksandrMaslov commented on RevitSpacesManager/ViewModels/Commands/CreateAllCommand.cs
> +        public AreaModel Model { get; set; }
Упустил момент, благодарю

2022-11-21 08:55 UTC, PavelAltynnikov approved these changes

2022-11-21 16:02 UTC, merged